server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/code2025?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# application.yml
deepseek:
  api-key: sk-fdd9196852e74707918fcaf2c03e0457 # 注意：冒号后必须加一个空格
  api-url:  https://api.deepseek.com/v1  # 冒号后加空格
  model: deepseek-chat  # 示例模型名，根据实际情况修改